{{- if eq .Values.rbac.scope "Namespaced" }}
{{- $namespaces := include "elasti.rbacNamespaces" . | fromYamlArray }}
{{- if .Values.rbac.useClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elasti.fullname" . }}-operator-manager-role
  labels:
    {{- include "elasti-operator.commonLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-operator.commonAnnotations" . | nindent 4 }}
rules:
{{- include "elasti.operatorManagerRules" . | nindent 0 }}
{{- else }}
{{- range $ns := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "elasti.fullname" $ }}-operator-manager-role
  namespace: {{ $ns }}
  labels:
    {{- include "elasti-operator.commonLabels" $ | nindent 4 }}
  annotations:
    {{- include "elasti-operator.commonAnnotations" $ | nindent 4 }}
rules:
{{- include "elasti.operatorManagerRules" $ | nindent 0 }}
{{- end }}
{{- end }}
{{- range $ns := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "elasti.fullname" $ }}-operator-manager-rolebinding
  namespace: {{ $ns }}
  labels:
    {{- include "elasti-operator.commonLabels" $ | nindent 4 }}
  annotations:
    {{- include "elasti-operator.commonAnnotations" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if $.Values.rbac.useClusterRole }}ClusterRole{{ else }}Role{{ end }}
  name: {{ include "elasti.fullname" $ }}-operator-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "elasti.fullname" $ }}-operator-controller-manager
  namespace: '{{ $.Release.Namespace }}'
{{- end }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elasti.fullname" . }}-operator-manager-role
  labels:
    {{- include "elasti-operator.commonLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-operator.commonAnnotations" . | nindent 4 }}
rules:
{{- include "elasti.operatorManagerRules" . | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elasti.fullname" . }}-operator-manager-rolebinding
  labels:
    {{- include "elasti-operator.commonLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-operator.commonAnnotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "elasti.fullname" . }}-operator-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "elasti.fullname" . }}-operator-controller-manager
  namespace: '{{ .Release.Namespace }}'
{{- end }}
